max_width = 100
comment_width = 100
use_small_heuristics = "Max"

imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

wrap_comments = true
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true

format_macro_matchers = true
condense_wildcard_suffixes = true
edition = "2021"

ignore = []
