[package]
name = "inner-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[dependencies]
syn = "2.0.87"
quote = "1.0.37"
proc-macro2 = "1.0.89"
proc-macro2-diagnostics = "0.10.1"
